# Problem 2: Even Fibonacci Numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# generate Fibonacci sequence and go through all even numbers, return sum
def getEvenFibSum(maxVal):
    evenSum = 0
    sequence = [1, 2]
    while sequence[-1] < maxVal:
        sequence.append(sequence[-1] + sequence[-2])
    for fibVal in sequence:
        if fibVal % 2 == 0:
            evenSum += fibVal
    return evenSum

print(getEvenFibSum(4000000))